### ISSUE TITLE
How do you join members to swarm?

### ISSUE THREAD

**Issue by artisticcheese** [pscripted/cDSCDockerSwarm#3]
I don't see an option to enter Swarm token to join swarm, how clients manage to join swarm as workers? I think there shall be 2 different resources one for Swarmmanagers and one for Swarm workers where managers will require input of swarm manager token and workers will need swarm worker token.

**Comment by pscripted** [comment]
The IP listed in the configuration is used by all other nodes to retrieve the manager and worker join tokens dynamically when the join. How nodes join is based on the    
 ManagerCount and SwarmManagement properties. 

With swarmManagement in Automatic, the DSC nodes will check how many managers already exist, and join as needed as a manager or worker depending on the ManagerCount set. Otherwise, swarm nodes will only join as workers.
